website_profile_fix/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes([
    'register' => false, // Register Routes...

    'reset' => false, // Reset Password Routes...

    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/front', function () {
    return redirect('/home');
});

Route::group(['namespace'=>'Backend'], function () {
    Route::prefix('dashboard')->group(function () {
        Route::resource('/', '\App\Http\Controllers\Backend\IndexController');
        Route::resource('/carousel', '\App\Http\Controllers\Backend\CarouselController');
        Route::resource('/pegawai', '\App\Http\Controllers\Backend\PegawaiController');
        //Route::resource('/berita', '\App\Http\Controllers\Backend\BeritaController');
        Route::resource('/sarana', '\App\Http\Controllers\Backend\SaranaController');
        Route::resource('/jabatan', '\App\Http\Controllers\Backend\MatpelController');
        Route::resource('/event', '\App\Http\Controllers\Backend\EventController');
        Route::resource('/data', '\App\Http\Controllers\Backend\DataController');
        Route::resource('/kontak', '\App\Http\Controllers\Backend\KontakController');
        Route::resource('/user', '\App\Http\Controllers\Backend\UserController');
        Route::resource('/profile', '\App\Http\Controllers\Backend\ProfileController');
        Route::resource('/password', '\App\Http\Controllers\Backend\PasswordController');
        Route::resource('/cms', '\App\Http\Controllers\Backend\CMSController');
        Route::resource('/import_data', '\App\Http\Controllers\Backend\ImportExcelController');
        Route::post('profile/update_password', '\App\Http\Controllers\Backend\ProfileController@update_password');
        Route::post('data/delete', '\App\Http\Controllers\Backend\DataController@delete')->name('data.delete');
        //Route::post('data/{search}', '\App\Http\Controllers\Backend\DataController@search')->name('search');
        Route::get('/dashboard', '\App\Http\Controllers\Backend\IndexController@index')->name('dashboard');

    });
});

Route::group(['namespace'=>'Frontend'], function () {
    Route::prefix('/')->group(function () {
        Route::resource('/', '\App\Http\Controllers\Frontend\IndexController');
        Route::resource('/fprofile', '\App\Http\Controllers\Frontend\FProfileController');
        Route::resource('/fkontak', '\App\Http\Controllers\Frontend\FKontakController');
        Route::resource('/fsarpras', '\App\Http\Controllers\Frontend\FSaranaController');
        Route::resource('/fpegawai', '\App\Http\Controllers\Frontend\FPegawaiController');
        Route::resource('/fevent', '\App\Http\Controllers\Frontend\FEventController');
        Route::get('/', '\App\Http\Controllers\Frontend\IndexController@index')->name('homepage');
        Route::get('/fprofile', '\App\Http\Controllers\Frontend\FProfileController@index')->name('profilepage');
        Route::get('/fkontak', '\App\Http\Controllers\Frontend\FKontakController@index')->name('kontakpage');
        Route::get('/fsarpras', '\App\Http\Controllers\Frontend\FSaranaController@index')->name('saranapage');
        Route::get('/fpegawai', '\App\Http\Controllers\Frontend\FPegawaiController@index')->name('pegawaipage');
        Route::get('/fevent', '\App\Http\Controllers\Frontend\FEventController@index')->name('eventpage');   
        Route::get('/fevent/{id}', '\App\Http\Controllers\Frontend\FEventController@show')->name('fevent');  
        Route::get('/fsarpras/{id}', '\App\Http\Controllers\Frontend\FSaranaController@show')->name('fsarpras');

    });
});

website_profile_fix/app/Models/Profile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    use HasFactory;
    protected $table = 'profiles';
}

website_profile_fix/app/Http/Controllers/Backend/BeritaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BeritaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        /*$this->middleware('admin'); /*Hak Akses Super Admin*/
    }
    public function index()
    {
        return view('backend.berita.index');
    }
}

website_profile_fix/app/Http/Controllers/Backend/CMSController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Profile;

class CMSController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        //$this->middleware('admin'); /*Hak Akses Super Admin*/
    }
    public function index()
    {
        $profile = DB::table('profiles')->paginate(5);
        return view('backend.cms.index',compact('profile'));
    }
    public function create()
    {
        $profile = null;
        return view('backend.cms.create',compact('profile'));
    }
    public function edit($id)
    {
        $profile = DB::table('profiles')->where('id',$id)->first();
        return view('backend.cms.edit',compact('profile'));
    }
    public function store(Request $request)
    {
        $profile = new Profile;
        $file           = $request->file('sekolah_img');
        $nama_file      = $file->getClientOriginalName();
        $file->move('backend/assets/img/',$file->getClientOriginalName());
        $profile->sekolah_img = $nama_file;
        $profile->sejarah = $request->sejarah;
        $file1           = $request->file('logo');
        $nama_file1      = $file1->getClientOriginalName();
        $file1->move('backend/assets/img/',$file1->getClientOriginalName());
        $profile->logo = $nama_file1;
        $profile->arti_logo = $request->arti_logo;
        $profile->visi = $request->visi;
        $profile->misi = $request->misi;
        $file2           = $request->file('kepsek_img');
        $nama_file2      = $file2->getClientOriginalName();
        $file2->move('backend/assets/img/',$file2->getClientOriginalName());
        $profile->kepsek_img = $nama_file2;
        $profile->kepsek_nama = $request->kepsek_nama;
        $file3           = $request->file('wakepsek1_img');
        $nama_file3      = $file3->getClientOriginalName();
        $file3->move('backend/assets/img/',$file3->getClientOriginalName());
        $profile->wakepsek1_img = $nama_file3;
        $profile->wakepsek1_nama = $request->wakepsek1_nama;
        $file4           = $request->file('wakepsek2_img');
        $nama_file4      = $file4->getClientOriginalName();
        $file4->move('backend/assets/img/',$file4->getClientOriginalName());
        $profile->wakepsek2_img = $nama_file4;
        $profile->wakepsek2_nama = $request->wakepsek2_nama;
        $profile->save();

        return redirect()->route('cms.index')->with('success','Data Telah Berhasil Ditambah.');
    }

    public function update($id, Request $request)
    {
        $profile = Profile::find($id);

        if($request->hasFile('sekolah_img')){
            $file           = $request->file('sekolah_img');
            $nama_file      = $file->getClientOriginalName();
            $file->move('backend/assets/img/',$file->getClientOriginalName());
            $profile->sekolah_img = $nama_file;
        }
        if($request->hasFile('logo')){
            $file1           = $request->file('logo');
            $nama_file1      = $file1->getClientOriginalName();
            $file1->move('backend/assets/img/',$file1->getClientOriginalName());
            $profile->logo = $nama_file1;
        }
        if($request->hasFile('kepsek_img')){
            $file2           = $request->file('kepsek_img');
            $nama_file2      = $file2->getClientOriginalName();
            $file2->move('backend/assets/img/',$file2->getClientOriginalName());
            $profile->kepsek_img = $nama_file2;
        }
        if($request->hasFile('wakepsek1_img')){
            $file3           = $request->file('wakepsek1_img');
            $nama_file3     = $file3->getClientOriginalName();
            $file3->move('backend/assets/img/',$file3->getClientOriginalName());
            $profile->wakepsek1_img = $nama_file3;
        }
        if($request->hasFile('wakepsek2_img')){
            $file4           = $request->file('wakepsek2_img');
            $nama_file4     = $file4->getClientOriginalName();
            $file4->move('backend/assets/img/',$file4->getClientOriginalName());
            $profile->wakepsek2_img = $nama_file4;
        }

        $profile->sejarah = $request->sejarah;
        $profile->arti_logo = $request->arti_logo;
        $profile->visi = $request->visi;
        $profile->misi = $request->misi;
        $profile->kepsek_nama = $request->kepsek_nama;
        $profile->wakepsek1_nama = $request->wakepsek1_nama;
        $profile->wakepsek2_nama = $request->wakepsek2_nama;
        $profile->save();

        return redirect()->route('cms.index')->with('success','Data Telah Berhasil Diperbarui.');
    }

}

website_profile_fix/app/Http/Controllers/Backend/CarouselController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Carousel;

class CarouselController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        //$this->middleware('admi'); /*Hak Akses Super Admin*/
    }
    public function index()
    {
        $carousel = DB::table('carousels')->paginate(5);
        return view('backend.carousel.index',compact('carousel'));
    }
    public function create()
    {
        $carousel = null;
        return view('backend.carousel.create',compact('carousel'));
    }
    public function edit($id)
    {
        $carousel = DB::table('carousels')->where('id',$id)->first();
        return view('backend.carousel.edit',compact('carousel'));
    }
    public function store(Request $request)
    {
        $carousel = new Carousel;
        $file           = $request->file('logo');
        $nama_file      = $file->getClientOriginalName();
        $file->move('backend/assets/img/',$file->getClientOriginalName());
        $carousel->judul = $request->judul;
        $carousel->desc = $request->desc;
        $carousel->image = $nama_file;
        $carousel->save();

        return redirect()->route('carousel.index')->with('success','Data Telah Berhasil Ditambah.');
    }

    public function update($id, Request $request)
    {
        $carousel = Carousel::find($id);

        if($request->hasFile('image')){
            $file           = $request->file('image');
            $nama_file      = $file->getClientOriginalName();
            $file->move('backend/assets/img/',$file->getClientOriginalName());
            $carousel->image = $nama_file;

        }
        $carousel->judul = $request->judul;
        $carousel->desc = $request->desc;
        $carousel->save();

        return redirect()->route('carousel.index')->with('success','Data Telah Berhasil Diperbarui.');
    }
}

website_profile_fix/app/Http/Controllers/Backend/DataController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Imports\SiswaImport;
use App\Models\Siswa;
use Maatwebsite\Excel\Facades\Excel;

class DataController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        /*$this->middleware('admin'); /*Hak Akses Super Admin*/
    }
    public function index()
    {
        $siswa = DB::table('students')->paginate(25);
        return view('backend.data.index',compact('siswa'));
    }
    public function store(Request $request)
	{
		// validasi
		$this->validate($request, [
			'file' => 'required|mimes:csv,xls,xlsx'
		]);

		// menangkap file excel
		$file = $request->file('file');

		// membuat nama file unik
		$nama_file = rand().$file->getClientOriginalName();

		// upload ke folder file_siswa di dalam folder public
		$file->move('file_siswa',$nama_file);

		// import data
		Excel::import(new SiswaImport, public_path('/file_siswa/'.$nama_file));

        return redirect()->route('data.index')->with('success','Data Telah Berhasil Ditambah.');
	}
    public function delete(){
        Siswa::truncate();
        return redirect()->route('data.index')->with('success','Data Telah Berhasil Dihapus.');
    }

}

website_profile_fix/app/Http/Controllers/Backend/EventController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Event;

class EventController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        //$this->middleware('admin'); /*Hak Akses Super Admin*/
    }
    public function index()
    {
        $event = DB::table('events')->paginate(5);
        return view('backend.event.index',compact('event'));
    }
    public function create()
    {
        $event = null;
        return view('backend.event.create',compact('event'));
    }
    public function edit($id)
    {
        $event = DB::table('events')->where('id',$id)->first();
        return view('backend.event.edit',compact('event'));
    }
    public function store(Request $request)
    {
        $request->validate([
            'isi' => 'required',
        ]);
        $event = new Event;
        $file           = $request->file('image');
        $nama_file      = $file->getClientOriginalName();
        $file->move('backend/assets/img/',$file->getClientOriginalName());
        $event->judul = $request->judul;
        $event->isi = $request->isi;
        $event->id_user = $request->id_user;
        $event->cover = $nama_file;
        $event->save();

        return redirect()->route('event.index')->with('success','Data Telah Berhasil Ditambah.');
    }

    public function update($id, Request $request)
    {
        $event = Event::find($id);
        if($request->hasFile('image')){
            $file           = $request->file('image');
            $nama_file      = $file->getClientOriginalName();
            $file->move('backend/assets/img/',$file->getClientOriginalName());
            $event->cover = $nama_file;
        }
        $event->judul = $request->judul;
        $event->isi = $request->isi;
        $event->save();

        return redirect()->route('event.index')->with('success','Data Telah Berhasil Diperbarui.');
    }

    public function destroy($id)
    {
        $event = Event::find($id);
        $event->delete();
        return redirect()->route('event.index')->with('success','Data Berhasil Dihapus');
    }
}

website_profile_fix/app/Http/Controllers/Backend/ImportExcelController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ImportExcelController extends Controller
{
    //
}

website_profile_fix/app/Http/Controllers/Backend/IndexController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\Models\Carousel;
use App\Models\User;
use App\Models\Pegawai;
use App\Models\Event;
use App\Models\Siswa;
use App\Models\Sarana;

class IndexController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        /*$this->middleware('admin'); /*Hak Akses Super Admin*/
    }
    public function index()
    {   
        $siswa = Siswa::count();
        $sarana = Sarana::count();
        $news = Event::latest()->take(5)->get();
        $event = Event::count();
        $pegawai = Pegawai::count();
        $user = User::count();
        $carousel = Carousel::all();
        $query1 = Siswa::where('kelas', 7)->count();
        $query2 = Siswa::where('kelas', 8)->count();
        $query3 = Siswa::where('kelas', 9)->count();
        return view('backend.index',
        compact(
        'carousel',
        'user',
        'pegawai',
        'event',
        'news',
        'sarana',
        'siswa',
        'query1',
        'query2',
        'query3'));
    }
    
}

website_profile_fix/app/Http/Controllers/Backend/PasswordController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class PasswordController extends Controller
{
    //
    public function update($id, Request $request)
    {
        $user = User::find($id);
        $user->password = Hash::make($request->password);
        $user->save();
        return redirect()->route('profile.index')->with('success','Data Telah Diperbarui');
    }
}

website_profile_fix/resources/views/backend/profile/index.blade.php
@extends('backend.layouts.template')

@section('title')
    <title>Dashboard - Profile User</title>
@endsection

@section('actdash')
    <a class="nav-link collapsed" href="{{ route('index') }}">
@endsection

@section('actcar')
    <a class="nav-link collapsed" href="{{ route('carousel.index') }}">
@endsection

@section('actdata')
    <a class="nav-link collapsed" href="{{ route('data.index') }}">
@endsection

@section('actevent')
    <a class="nav-link collapsed" href="{{ route('event.index') }}">
@endsection

@section('actkontak')
    <a class="nav-link collapsed" href="{{ route('kontak.index') }}">
@endsection

@section('actmatpel')
    <a class="nav-link collapsed" href="{{ route('jabatan.index') }}">
@endsection

@section('actpegawai')
    <a class="nav-link collapsed" href="{{ route('pegawai.index') }}">
@endsection

@section('actsarana')
    <a class="nav-link collapsed" href="{{ route('sarana.index') }}">
@endsection

@section('actuser')
    <a class="nav-link collapsed" href="{{ route('user.index') }}">
@endsection

@section('actprofil')
    <a class="nav-link collapsed" href="{{ route('cms.index') }}">
@endsection

@section('content')
@if (session('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">{{session('success')}}</h4>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
@endif
    <div class="pagetitle">
    <h1>Profile</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('index') }}">Home</a></li>
        <li class="breadcrumb-item active">Profile User</li>
      </ol>
    </nav>
    </div><!-- End Page Title -->

    <section class="section profile">
        <div class="row">
          <div class="col-xl-4">

            <div class="card">
              <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

                <img src="{{ URL::to('backend/assets/img/', $user->image) }}" alt="Profile" class="rounded-circle">
                <h2>{{$user->name}}</h2>
                <h3>{{$user->role}}</h3>
                <!--<div class="social-links mt-2">
                  <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                  <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                  <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                  <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                </div>-->
              </div>
            </div>

          </div>

          <div class="col-xl-8">

            <div class="card">
              <div class="card-body pt-3">
                <!-- Bordered Tabs -->
                <ul class="nav nav-tabs nav-tabs-bordered">

                  <li class="nav-item">
                    <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                  </li>

                  <li class="nav-item">
                    <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Edit Profile</button>
                  </li>

                  <!--<li class="nav-item">
                    <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-settings">Settings</button>
                  </li>-->

                  <li class="nav-item">
                    <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">Change Password</button>
                  </li>

                </ul>
                <div class="tab-content pt-2">

                  <div class="tab-pane fade show active profile-overview" id="profile-overview">
                    {{--<h5 class="card-title">About</h5>
                    <p class="small fst-italic">Sunt est soluta temporibus accusantium neque nam maiores cumque temporibus. Tempora libero non est unde veniam est qui dolor. Ut sunt iure rerum quae quisquam autem eveniet perspiciatis odit. Fuga sequi sed ea saepe at unde.</p>--}}

                    <h5 class="card-title">Profile Details</h5>

                    <div class="row">
                      <div class="col-lg-3 col-md-4 label ">Nama</div>
                      <div class="col-lg-9 col-md-8">{{$user->name}}</div>
                    </div>

                    <div class="row">
                      <div class="col-lg-3 col-md-4 label">Role</div>
                      <div class="col-lg-9 col-md-8">{{$user->role}}</div>
                    </div>

                    <div class="row">
                      <div class="col-lg-3 col-md-4 label">Email</div>
                      <div class="col-lg-9 col-md-8">{{$user->email}}</div>
                    </div>

                  </div>

                  <div class="tab-pane fade profile-edit pt-3" id="profile-edit">

                    <!-- Profile Edit Form -->
                    <form method="POST" action="{{ route('profile.update',$user->id) }}" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                      <div class="row mb-3">
                        <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile Image</label>
                        <div class="col-md-8 col-lg-9">
                            <div class="pt-2">
                                <input class="form-control" type="file" id="formFile" name="image">
                                <!--<input type="file" id="profile-image" hidden name="image">-->
                                <!--<a href="" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></a>-->
                            </div>
                        </div>
                      </div>

                      <div class="row mb-3">
                        <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Name</label>
                        <div class="col-md-8 col-lg-9">
                          <input name="name" type="text" class="form-control" id="fullName" value="{{$user->name}}">
                        </div>
                      </div>

                      <input name="role" type="hidden" class="form-control" id="Job" value="{{$user->role}}">

                      <div class="row mb-3">
                        <label for="Email" class="col-md-4 col-lg-3 col-form-label">Email</label>
                        <div class="col-md-8 col-lg-9">
                          <input name="email" type="email" class="form-control" id="Email" value="{{$user->email}}">
                        </div>
                      </div>

                      <div class="text-center">
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                      </div>
                    </form><!-- End Profile Edit Form -->

                  </div>

                  <div class="tab-pane fade pt-3" id="profile-settings">

                    <!-- Settings Form
                    <form>

                      <div class="row mb-3">
                        <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email Notifications</label>
                        <div class="col-md-8 col-lg-9">
                          <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="changesMade" checked>
                            <label class="form-check-label" for="changesMade">
                              Changes made to your account
                            </label>
                          </div>
                          <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="newProducts" checked>
                            <label class="form-check-label" for="newProducts">
                              Information on new products and services
                            </label>
                          </div>
                          <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="proOffers">
                            <label class="form-check-label" for="proOffers">
                              Marketing and promo offers
                            </label>
                          </div>
                          <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="securityNotify" checked disabled>
                            <label class="form-check-label" for="securityNotify">
                              Security alerts
                            </label>
                          </div>
                        </div>
                      </div>

                      <div class="text-center">
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                      </div>
                    </form> End settings Form -->

                  </div>

                  <div class="tab-pane fade pt-3" id="profile-change-password">
                    <!-- Change Password Form -->
                    <form method="POST" action="{{ route('password.update',$user->id) }}" oninput='confirmPassword.setCustomValidity(confirmPassword.value != password.value ? "Passwords do not match." : "")'>
                    @csrf
                    @method('PUT')

                      <!--<div class="row mb-3">
                        <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                        <div class="col-md-8 col-lg-9">
                          <input name="password" type="password" class="form-control" id="currentPassword">
                        </div>
                      </div>-->

                      <div class="row mb-3">
                        <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                        <div class="col-md-8 col-lg-9">
                          <input name="password" type="password" class="form-control" id="newPassword" required>
                        </div>
                      </div>

                      <div class="text-center">
                        <button type="submit" class="btn btn-primary">Change Password</button>
                      </div>
                    </form><!-- End Change Password Form -->

                  </div>

                </div><!-- End Bordered Tabs -->

              </div>
            </div>

          </div>
        </div>
    </section>

@endsection