website_profile_fix/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes([
    'register' => false, // Register Routes...

    'reset' => false, // Reset Password Routes...

    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/front', function () {
    return redirect('/home');
});

Route::group(['namespace'=>'Backend'], function () {
    Route::prefix('dashboard')->group(function () {
        Route::resource('/', '\App\Http\Controllers\Backend\IndexController');
        Route::resource('/carousel', '\App\Http\Controllers\Backend\CarouselController');
        Route::resource('/pegawai', '\App\Http\Controllers\Backend\PegawaiController');
        //Route::resource('/berita', '\App\Http\Controllers\Backend\BeritaController');
        Route::resource('/sarana', '\App\Http\Controllers\Backend\SaranaController');
        Route::resource('/jabatan', '\App\Http\Controllers\Backend\MatpelController');
        Route::resource('/event', '\App\Http\Controllers\Backend\EventController');
        Route::resource('/data', '\App\Http\Controllers\Backend\DataController');
        Route::resource('/kontak', '\App\Http\Controllers\Backend\KontakController');
        Route::resource('/user', '\App\Http\Controllers\Backend\UserController');
        Route::resource('/profile', '\App\Http\Controllers\Backend\ProfileController');
        Route::resource('/password', '\App\Http\Controllers\Backend\PasswordController');
        Route::resource('/cms', '\App\Http\Controllers\Backend\CMSController');
        Route::resource('/import_data', '\App\Http\Controllers\Backend\ImportExcelController');
        Route::post('profile/update_password', '\App\Http\Controllers\Backend\ProfileController@update_password');
        Route::post('data/delete', '\App\Http\Controllers\Backend\DataController@delete')->name('data.delete');
        //Route::post('data/{search}', '\App\Http\Controllers\Backend\DataController@search')->name('search');
        Route::get('/dashboard', '\App\Http\Controllers\Backend\IndexController@index')->name('dashboard');

    });
});

Route::group(['namespace'=>'Frontend'], function () {
    Route::prefix('/')->group(function () {
        Route::resource('/', '\App\Http\Controllers\Frontend\IndexController');
        Route::resource('/fprofile', '\App\Http\Controllers\Frontend\FProfileController');
        Route::resource('/fkontak', '\App\Http\Controllers\Frontend\FKontakController');
        Route::resource('/fsarpras', '\App\Http\Controllers\Frontend\FSaranaController');
        Route::resource('/fpegawai', '\App\Http\Controllers\Frontend\FPegawaiController');
        Route::resource('/fevent', '\App\Http\Controllers\Frontend\FEventController');
        Route::get('/', '\App\Http\Controllers\Frontend\IndexController@index')->name('homepage');
        Route::get('/fprofile', '\App\Http\Controllers\Frontend\FProfileController@index')->name('profilepage');
        Route::get('/fkontak', '\App\Http\Controllers\Frontend\FKontakController@index')->name('kontakpage');
        Route::get('/fsarpras', '\App\Http\Controllers\Frontend\FSaranaController@index')->name('saranapage');
        Route::get('/fpegawai', '\App\Http\Controllers\Frontend\FPegawaiController@index')->name('pegawaipage');
        Route::get('/fevent', '\App\Http\Controllers\Frontend\FEventController@index')->name('eventpage');   
        Route::get('/fevent/{id}', '\App\Http\Controllers\Frontend\FEventController@show')->name('fevent');  
        Route::get('/fsarpras/{id}', '\App\Http\Controllers\Frontend\FSaranaController@show')->name('fsarpras');

    });
});

website_profile_fix/app/Http/Controllers/Backend/BeritaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BeritaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        /*$this->middleware('admin'); /*Hak Akses Super Admin*/
    }
    public function index()
    {
        return view('backend.berita.index');
    }
}

website_profile_fix/app/Http/Controllers/Backend/CMSController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Profile;

class CMSController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        //$this->middleware('admin'); /*Hak Akses Super Admin*/
    }
    public function index()
    {
        $profile = DB::table('profiles')->paginate(5);
        return view('backend.cms.index',compact('profile'));
    }
    public function create()
    {
        $profile = null;
        return view('backend.cms.create',compact('profile'));
    }
    public function edit($id)
    {
        $profile = DB::table('profiles')->where('id',$id)->first();
        return view('backend.cms.edit',compact('profile'));
    }
    public function store(Request $request)
    {
        $profile = new Profile;
        $file           = $request->file('sekolah_img');
        $nama_file      = $file->getClientOriginalName();
        $file->move('backend/assets/img/',$file->getClientOriginalName());
        $profile->sekolah_img = $nama_file;
        $profile->sejarah = $request->sejarah;
        $file1           = $request->file('logo');
        $nama_file1      = $file1->getClientOriginalName();
        $file1->move('backend/assets/img/',$file1->getClientOriginalName());
        $profile->logo = $nama_file1;
        $profile->arti_logo = $request->arti_logo;
        $profile->visi = $request->visi;
        $profile->misi = $request->misi;
        $file2           = $request->file('kepsek_img');
        $nama_file2      = $file2->getClientOriginalName();
        $file2->move('backend/assets/img/',$file2->getClientOriginalName());
        $profile->kepsek_img = $nama_file2;
        $profile->kepsek_nama = $request->kepsek_nama;
        $file3           = $request->file('wakepsek1_img');
        $nama_file3      = $file3->getClientOriginalName();
        $file3->move('backend/assets/img/',$file3->getClientOriginalName());
        $profile->wakepsek1_img = $nama_file3;
        $profile->wakepsek1_nama = $request->wakepsek1_nama;
        $file4           = $request->file('wakepsek2_img');
        $nama_file4      = $file4->getClientOriginalName();
        $file4->move('backend/assets/img/',$file4->getClientOriginalName());
        $profile->wakepsek2_img = $nama_file4;
        $profile->wakepsek2_nama = $request->wakepsek2_nama;
        $profile->save();

        return redirect()->route('cms.index')->with('success','Data Telah Berhasil Ditambah.');
    }

    public function update($id, Request $request)
    {
        $profile = Profile::find($id);

        if($request->hasFile('sekolah_img')){
            $file           = $request->file('sekolah_img');
            $nama_file      = $file->getClientOriginalName();
            $file->move('backend/assets/img/',$file->getClientOriginalName());
            $profile->sekolah_img = $nama_file;
        }
        if($request->hasFile('logo')){
            $file1           = $request->file('logo');
            $nama_file1      = $file1->getClientOriginalName();
            $file1->move('backend/assets/img/',$file1->getClientOriginalName());
            $profile->logo = $nama_file1;
        }
        if($request->hasFile('kepsek_img')){
            $file2           = $request->file('kepsek_img');
            $nama_file2      = $file2->getClientOriginalName();
            $file2->move('backend/assets/img/',$file2->getClientOriginalName());
            $profile->kepsek_img = $nama_file2;
        }
        if($request->hasFile('wakepsek1_img')){
            $file3           = $request->file('wakepsek1_img');
            $nama_file3     = $file3->getClientOriginalName();
            $file3->move('backend/assets/img/',$file3->getClientOriginalName());
            $profile->wakepsek1_img = $nama_file3;
        }
        if($request->hasFile('wakepsek2_img')){
            $file4           = $request->file('wakepsek2_img');
            $nama_file4     = $file4->getClientOriginalName();
            $file4->move('backend/assets/img/',$file4->getClientOriginalName());
            $profile->wakepsek2_img = $nama_file4;
        }

        $profile->sejarah = $request->sejarah;
        $profile->arti_logo = $request->arti_logo;
        $profile->visi = $request->visi;
        $profile->misi = $request->misi;
        $profile->kepsek_nama = $request->kepsek_nama;
        $profile->wakepsek1_nama = $request->wakepsek1_nama;
        $profile->wakepsek2_nama = $request->wakepsek2_nama;
        $profile->save();

        return redirect()->route('cms.index')->with('success','Data Telah Berhasil Diperbarui.');
    }

}

website_profile_fix/app/Http/Controllers/Backend/CarouselController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Carousel;

class CarouselController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        //$this->middleware('admi'); /*Hak Akses Super Admin*/
    }
    public function index()
    {
        $carousel = DB::table('carousels')->paginate(5);
        return view('backend.carousel.index',compact('carousel'));
    }
    public function create()
    {
        $carousel = null;
        return view('backend.carousel.create',compact('carousel'));
    }
    public function edit($id)
    {
        $carousel = DB::table('carousels')->where('id',$id)->first();
        return view('backend.carousel.edit',compact('carousel'));
    }
    public function store(Request $request)
    {
        $carousel = new Carousel;
        $file           = $request->file('logo');
        $nama_file      = $file->getClientOriginalName();
        $file->move('backend/assets/img/',$file->getClientOriginalName());
        $carousel->judul = $request->judul;
        $carousel->desc = $request->desc;
        $carousel->image = $nama_file;
        $carousel->save();

        return redirect()->route('carousel.index')->with('success','Data Telah Berhasil Ditambah.');
    }

    public function update($id, Request $request)
    {
        $carousel = Carousel::find($id);

        if($request->hasFile('image')){
            $file           = $request->file('image');
            $nama_file      = $file->getClientOriginalName();
            $file->move('backend/assets/img/',$file->getClientOriginalName());
            $carousel->image = $nama_file;

        }
        $carousel->judul = $request->judul;
        $carousel->desc = $request->desc;
        $carousel->save();

        return redirect()->route('carousel.index')->with('success','Data Telah Berhasil Diperbarui.');
    }
}

website_profile_fix/app/Http/Controllers/Backend/DataController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Imports\SiswaImport;
use App\Models\Siswa;
use Maatwebsite\Excel\Facades\Excel;

class DataController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        /*$this->middleware('admin'); /*Hak Akses Super Admin*/
    }
    public function index()
    {
        $siswa = DB::table('students')->paginate(25);
        return view('backend.data.index',compact('siswa'));
    }
    public function store(Request $request)
	{
		// validasi
		$this->validate($request, [
			'file' => 'required|mimes:csv,xls,xlsx'
		]);

		// menangkap file excel
		$file = $request->file('file');

		// membuat nama file unik
		$nama_file = rand().$file->getClientOriginalName();

		// upload ke folder file_siswa di dalam folder public
		$file->move('file_siswa',$nama_file);

		// import data
		Excel::import(new SiswaImport, public_path('/file_siswa/'.$nama_file));

        return redirect()->route('data.index')->with('success','Data Telah Berhasil Ditambah.');
	}
    public function delete(){
        Siswa::truncate();
        return redirect()->route('data.index')->with('success','Data Telah Berhasil Dihapus.');
    }

}

website_profile_fix/app/Http/Controllers/Backend/EventController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Event;

class EventController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        //$this->middleware('admin'); /*Hak Akses Super Admin*/
    }
    public function index()
    {
        $event = DB::table('events')->paginate(5);
        return view('backend.event.index',compact('event'));
    }
    public function create()
    {
        $event = null;
        return view('backend.event.create',compact('event'));
    }
    public function edit($id)
    {
        $event = DB::table('events')->where('id',$id)->first();
        return view('backend.event.edit',compact('event'));
    }
    public function store(Request $request)
    {
        $request->validate([
            'isi' => 'required',
        ]);
        $event = new Event;
        $file           = $request->file('image');
        $nama_file      = $file->getClientOriginalName();
        $file->move('backend/assets/img/',$file->getClientOriginalName());
        $event->judul = $request->judul;
        $event->isi = $request->isi;
        $event->id_user = $request->id_user;
        $event->cover = $nama_file;
        $event->save();

        return redirect()->route('event.index')->with('success','Data Telah Berhasil Ditambah.');
    }

    public function update($id, Request $request)
    {
        $event = Event::find($id);
        if($request->hasFile('image')){
            $file           = $request->file('image');
            $nama_file      = $file->getClientOriginalName();
            $file->move('backend/assets/img/',$file->getClientOriginalName());
            $event->cover = $nama_file;
        }
        $event->judul = $request->judul;
        $event->isi = $request->isi;
        $event->save();

        return redirect()->route('event.index')->with('success','Data Telah Berhasil Diperbarui.');
    }

    public function destroy($id)
    {
        $event = Event::find($id);
        $event->delete();
        return redirect()->route('event.index')->with('success','Data Berhasil Dihapus');
    }
}

website_profile_fix/app/Http/Controllers/Backend/ImportExcelController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ImportExcelController extends Controller
{
    //
}

website_profile_fix/app/Http/Controllers/Backend/IndexController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\Models\Carousel;
use App\Models\User;
use App\Models\Pegawai;
use App\Models\Event;
use App\Models\Siswa;
use App\Models\Sarana;

class IndexController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); /*Hak Akses Login*/
        /*$this->middleware('admin'); /*Hak Akses Super Admin*/
    }
    public function index()
    {   
        $siswa = Siswa::count();
        $sarana = Sarana::count();
        $news = Event::latest()->take(5)->get();
        $event = Event::count();
        $pegawai = Pegawai::count();
        $user = User::count();
        $carousel = Carousel::all();
        $query1 = Siswa::where('kelas', 7)->count();
        $query2 = Siswa::where('kelas', 8)->count();
        $query3 = Siswa::where('kelas', 9)->count();
        return view('backend.index',
        compact(
        'carousel',
        'user',
        'pegawai',
        'event',
        'news',
        'sarana',
        'siswa',
        'query1',
        'query2',
        'query3'));
    }
    
}

website_profile_fix/app/Http/Controllers/Backend/PasswordController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class PasswordController extends Controller
{
    //
    public function update($id, Request $request)
    {
        $user = User::find($id);
        $user->password = Hash::make($request->password);
        $user->save();
        return redirect()->route('profile.index')->with('success','Data Telah Diperbarui');
    }
}

website_profile_fix/resources/views/backend/data/index.blade.php
@extends('backend.layouts.template')

@section('title')
    <title>Dashboard - Data Siswa </title>
@endsection

@section('actdash')
    <a class="nav-link collapsed" href="{{ route('index') }}">
@endsection

@section('actcar')
    <a class="nav-link collapsed" href="{{ route('carousel.index') }}">
@endsection

@section('actdata')
    <a class="nav-link " href="{{ route('data.index') }}">
@endsection

@section('actevent')
    <a class="nav-link collapsed" href="{{ route('event.index') }}">
@endsection

@section('actkontak')
    <a class="nav-link collapsed" href="{{ route('kontak.index') }}">
@endsection

@section('actmatpel')
    <a class="nav-link collapsed" href="{{ route('jabatan.index') }}">
@endsection

@section('actpegawai')
    <a class="nav-link collapsed" href="{{ route('pegawai.index') }}">
@endsection

@section('actsarana')
    <a class="nav-link collapsed" href="{{ route('sarana.index') }}">
@endsection

@section('actuser')
    <a class="nav-link collapsed" href="{{ route('user.index') }}">
@endsection

@section('actprofil')
    <a class="nav-link collapsed" href="{{ route('cms.index') }}">
@endsection

@section('content')
@if (session('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">{{session('success')}}</h4>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
@endif
<div class="pagetitle">
    <h1>Data Siswa</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('index') }}">Home</a></li>
        <li class="breadcrumb-item active">Data Siswa</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row">
      <div class="col-lg-12">

        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Data Siswa</h5>

            <!-- Table Data Siswa -->
            <table class="table table-hover datatable">
                <thead>
                  <tr class="table-light">
                    <th scope="col">#</th>
                    <th scope="col">NIS</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Jenis Kelamin</th>
                    <th scope="col">Kelas</th>
                    <th scope="col">Dibuat Saat</th>
                  </tr>
                </thead>
                <tbody>
                <?php $no = ($siswa->currentpage()-1)* $siswa->perpage() + 1;?>
                  @foreach ($siswa as $item)
                  <tr class="table-light">
                    <th scope="row">{{$no++}}</th>
                    <td>{{$item->nis}}</td>
                    <td>{{$item->nama}}</td>
                    <td>{{$item->jk}}</td>
                    <td>{{$item->kelas}}</td>
                    <td>{{$item->created_at}}</td>
                  </tr>
                  @endforeach
                </tbody>
            </table>

              <!-- Centered Pagination -->
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                  <div class="col-1">
                    {!! $siswa->links()!!}
                  </div>
                </ul>
            </nav><!-- End Centered Pagination -->

            <!--<a href="{{ route('jabatan.create') }}"><button type="button" class="btn btn-primary"><i class="bi bi-plus-circle-fill"></i> Tambah</button></a>-->


            <form method="POST" action="{{route('data.delete')}}" enctype="multipart/form-data">
                {{ csrf_field() }}
                <button type="button" class="btn btn-primary mr-5" data-bs-toggle="modal" data-bs-target="#basicModal">
                    Import Excel
                </button>
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>

            <!-- Import Excel -->
            <div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <form method="POST" action="{{ route('data.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Import Excel</h5>
                            </div>
                            <div class="modal-body">



                                <label>Pilih file excel</label>
                                <div class="form-group">
                                    <input type="file" name="file" required="required">
                                </div>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Import</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

@endsection